#!/bin/bash

# Firstly install xinput
if [ ! -f /usr/bin/xinput ]
then
    echo "xinput is not installed. Installing xinput..."
    sudo pacman -S xorg-xinput
fi

# Set variable for touchscreen id
id=$(xinput --list | grep "Touchscreen" | grep -o 'id=[0-9]*' | awk -F= '{print $2}')

# Disabling touchscreen
xinput set-prop $id 'Device Enabled' 0
